# Generated by Django 2.1.3 on 2018-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costingapp', '0002_auto_20181128_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproduct',
            name='fulltitle',
            field=models.CharField(default='Jigsaw Listening Students', max_length=255),
            preserve_default=False,
        ),
    ]
