# Generated by Django 2.1.3 on 2018-11-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costingapp', '0003_tblproduct_fulltitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='tblproduct',
            name='productid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
