# Generated by Django 2.1.3 on 2019-02-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costingapp', '0005_tblproduct_isbn13'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltitle', models.CharField(max_length=255)),
                ('isbn13', models.CharField(max_length=13, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
