# Generated by Django 2.1.3 on 2019-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costingapp', '0006_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblProductPriceTypeCurrency',
            fields=[
                ('productpricetypecurrencyid', models.IntegerField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('pricetypeid', models.IntegerField()),
                ('currenyid', models.IntegerField()),
                ('pricevalue', models.FloatField()),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblproduct',
            name='firstimpproductid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tblproduct',
            name='fulltitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
