export const GET_TBLPRODUCT = "GET_TBLPRODUCT";
export const UPDATE_TBLPRODUCT = "UPDATE_TBLPRODUCT";
export const UPDATE_TBLPRODUCTFORM = "UPDATE_TBLPRODUCTFORM";
export const ADD_TBLPRODUCT = "ADD_TBLPRODUCT";
